services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: interndb
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - API_KEY=${API_KEY}
    depends_on:
      - db